// Generated by scripts/syncHairTrends.mjs. Do not hand-edit.
export const trendRegistrySnapshot = {
  "schemaVersion": 1,
  "registryVersion": "HLM-TRENDS-2026-07-1",
  "snapshotDate": "2026-07-29",
  "sourcePolicy": "metadata-only",
  "recordCount": 40,
  "records": [
    {
      "id": "HLM-TREND-F-L-01",
      "baseKo": "U라인 롱",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-L-01-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-L-03",
      "baseKo": "버터플라이 레이어",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-L-03-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-L-04",
      "baseKo": "롱 허쉬",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-L-04-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-L-05",
      "baseKo": "롱 샤그",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-L-05-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-L-06",
      "baseKo": "에어리 레이어드",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-L-06-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-L-09",
      "baseKo": "블런트 롱",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-L-09-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-MD-01",
      "baseKo": "블런트 로브",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-MD-01-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-MD-02",
      "baseKo": "허쉬 미디",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-MD-02-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-MD-03",
      "baseKo": "레이어드 미디",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-MD-03-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-MD-04",
      "baseKo": "울프 미디",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-MD-04-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-MD-05",
      "baseKo": "원랭스 미디",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-MD-05-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-MD-06",
      "baseKo": "페이스프레임 미디",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-MD-06-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-MD-07",
      "baseKo": "버터플라이 로브",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-MD-07-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-MD-08",
      "baseKo": "옥토퍼스 미디",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-MD-08-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-S-01",
      "baseKo": "프렌치 보브",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-S-01-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-S-02",
      "baseKo": "미니 보브",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-S-02-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-S-03",
      "baseKo": "턱선 블런트 보브",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-S-03-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-S-04",
      "baseKo": "그래듀에이티드 보브",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-S-04-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-S-05",
      "baseKo": "샤기 보브",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-S-05-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-F-S-07",
      "baseKo": "이탈리안 보브",
      "genderId": "F",
      "designIdPrefixes": [
        "HLM-C-F-S-07-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-L-02",
      "baseKo": "레이어드 장발",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-L-02-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-L-03",
      "baseKo": "서퍼 롱",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-L-03-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-MD-01",
      "baseKo": "미디엄 커튼",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-MD-01-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-MD-02",
      "baseKo": "미디엄 슬릭백",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-MD-02-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-MD-03",
      "baseKo": "미디엄 테이퍼",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-MD-03-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-MD-04",
      "baseKo": "울프컷",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-MD-04-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-MD-06",
      "baseKo": "브로 플로우",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-MD-06-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-MD-07",
      "baseKo": "소프트 멀릿",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-MD-07-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-MD-08",
      "baseKo": "미디엄 샤그",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-MD-08-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-S-01",
      "baseKo": "소프트 투블럭",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-S-01-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-S-02",
      "baseKo": "댄디컷",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-S-02-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-S-03",
      "baseKo": "텍스처드 크롭",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-S-03-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-S-05",
      "baseKo": "쉼표머리",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-S-05-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-S-06",
      "baseKo": "리프컷",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-S-06-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-S-08",
      "baseKo": "텍스처드 퀴프",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-S-08-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-S-10",
      "baseKo": "숏 모드컷",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-S-10-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-US-03",
      "baseKo": "아이비리그",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-US-03-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-US-06",
      "baseKo": "프렌치 크롭",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-US-06-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-US-09",
      "baseKo": "템플 페이드 크롭",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-US-09-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    },
    {
      "id": "HLM-TREND-M-US-10",
      "baseKo": "버스트 크롭",
      "genderId": "M",
      "designIdPrefixes": [
        "HLM-C-M-US-10-"
      ],
      "region": "KR",
      "score": 0.793,
      "sourceCount": 1,
      "sourceIds": [
        "hairloom-editorial-baseline-2026-07"
      ],
      "sourceTypes": [
        "stylist-curated"
      ],
      "observedAt": "2026-07-29",
      "rights": "metadata-only",
      "sampleCount": 0,
      "references": []
    }
  ]
};
